server.port=9090
# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/video.stream.app
spring.datasource.username=root
spring.datasource.password=Nimi@1999


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Max file size (single file)
spring.servlet.multipart.max-file-size=500MB

# Max request size (total request)
spring.servlet.multipart.max-request-size=500MB

files.video= videos/

files.video.hls= videos_hls/